/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista.paneles.principal;

//import co.edu.usbbog.datan.niote.vista.AddIoTNodeJPanel;
//import co.edu.usbbog.datan.niote.vista.LogicalCommunication;
//import co.edu.usbbog.datan.niote.vista.NavigationCommunication;
//import co.edu.usbbog.datan.niote.vista.MainJFrame;
import co.edu.usbbog.datan.niote.vista.Principal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Camilo y Roberth
 */
public class DynamicNodesPaletteJPanel extends javax.swing.JPanel {

    private List<JButton> nodes;
    private Integer indices;
    private Principal principal;
//    private AddIoTNodeJPanel agregarNodoIoTJPanel;
//    private NavigationCommunication navegacion;
//    private LogicalCommunication comunicacionLogica;

    /**
     * Creates new form PaletaNodosDinamicosJPanel
     */
    public DynamicNodesPaletteJPanel(Principal principal) {
        this.principal = principal;
//        this.comunicacionLogica = new LogicalCommunication();
//        this.navegacion = new NavigationCommunication();
        nodes = new ArrayList<>();
        indices = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneSensors = new javax.swing.JScrollPane();
        jPanelNodos = new javax.swing.JPanel();
        jButtonHumedity = new javax.swing.JButton();
        jButtonTemperature = new javax.swing.JButton();
        jButtonSpeed = new javax.swing.JButton();
        jButtonSound = new javax.swing.JButton();
        jButtonGPS = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPaneActuators = new javax.swing.JScrollPane();
        jPanelNodosActuators1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 27, 27));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/baseline_add_white_18dp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 40, 50));

        jPanelNodos.setBackground(new java.awt.Color(61, 61, 61));
        jPanelNodos.setLayout(new java.awt.GridLayout(0, 2));

        jButtonHumedity.setBackground(new java.awt.Color(45, 45, 45));
        jButtonHumedity.setForeground(new java.awt.Color(240, 240, 240));
        jButtonHumedity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Humidity Sensor.png"))); // NOI18N
        jButtonHumedity.setText("Humedad");
        jButtonHumedity.setContentAreaFilled(false);
        jButtonHumedity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHumedityActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButtonHumedity);

        jButtonTemperature.setForeground(new java.awt.Color(240, 240, 240));
        jButtonTemperature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Temperature Sensor.png"))); // NOI18N
        jButtonTemperature.setText("Temperatura");
        jButtonTemperature.setBorderPainted(false);
        jButtonTemperature.setContentAreaFilled(false);
        jButtonTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTemperatureActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButtonTemperature);

        jButtonSpeed.setForeground(new java.awt.Color(240, 240, 240));
        jButtonSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Speed Sensor.png"))); // NOI18N
        jButtonSpeed.setText("Velocidad");
        jButtonSpeed.setBorderPainted(false);
        jButtonSpeed.setContentAreaFilled(false);
        jButtonSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButtonSpeed);

        jButtonSound.setForeground(new java.awt.Color(240, 240, 240));
        jButtonSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Wave Sensor.png"))); // NOI18N
        jButtonSound.setText("Sonido");
        jButtonSound.setBorderPainted(false);
        jButtonSound.setContentAreaFilled(false);
        jButtonSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoundActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButtonSound);

        jButtonGPS.setForeground(new java.awt.Color(240, 240, 240));
        jButtonGPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/GPS Sensor.png"))); // NOI18N
        jButtonGPS.setText("GPS");
        jButtonGPS.setBorderPainted(false);
        jButtonGPS.setContentAreaFilled(false);
        jButtonGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGPSActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButtonGPS);

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Motion Sensor.png"))); // NOI18N
        jButton3.setText("Movimiento");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButton3);

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Smoke Sensor.png"))); // NOI18N
        jButton2.setText("Humo");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButton2);

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Water Sensor.png"))); // NOI18N
        jButton4.setText("Agua");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButton4);

        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Wind Sensor.png"))); // NOI18N
        jButton5.setText("Viento");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButton5);

        jScrollPaneSensors.setViewportView(jPanelNodos);

        jTabbedPane1.addTab("Sensores", jScrollPaneSensors);

        jPanelNodosActuators1.setBackground(new java.awt.Color(61, 61, 61));
        jPanelNodosActuators1.setLayout(new java.awt.GridLayout(0, 2));

        jButton12.setForeground(new java.awt.Color(240, 240, 240));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Air Conditioning Actuator.png"))); // NOI18N
        jButton12.setText("Aire Acondicionado");
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanelNodosActuators1.add(jButton12);

        jButton13.setForeground(new java.awt.Color(240, 240, 240));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Alarm Actuator.png"))); // NOI18N
        jButton13.setText("Alarma");
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanelNodosActuators1.add(jButton13);

        jButton14.setForeground(new java.awt.Color(240, 240, 240));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Fan Actuator.png"))); // NOI18N
        jButton14.setText("Ventilador");
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanelNodosActuators1.add(jButton14);

        jButton15.setForeground(new java.awt.Color(240, 240, 240));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/LED Actuator.png"))); // NOI18N
        jButton15.setText("LED");
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanelNodosActuators1.add(jButton15);

        jButton16.setForeground(new java.awt.Color(240, 240, 240));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/paletanodos/Motor Actuator.png"))); // NOI18N
        jButton16.setText("Motor");
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanelNodosActuators1.add(jButton16);

        jScrollPaneActuators.setViewportView(jPanelNodosActuators1);

        jTabbedPane1.addTab("Actuadores", jScrollPaneActuators);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 370, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        navegacion.goAddNewNode();
//        File imegen = navegacion.searchNewImagen();
////        JButton jButoon=new JButton("Boton con imagen", imegen.);
//        addNewBotton();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonHumedityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHumedityActionPerformed
        principal.addComponentEmulatorJPanel("Humidity Sensor", "Humidity Sensor");
        //agregarComponente("Agua");
    }//GEN-LAST:event_jButtonHumedityActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        principal.addComponentEmulatorJPanel("Air Conditioning Actuator", "Air Conditioning Actuator");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButtonTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTemperatureActionPerformed
        principal.addComponentEmulatorJPanel("Temperature Sensor", "Temperature Sensor");
    }//GEN-LAST:event_jButtonTemperatureActionPerformed

    private void jButtonSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedActionPerformed
        principal.addComponentEmulatorJPanel("Speed Sensor", "Speed Sensor");
    }//GEN-LAST:event_jButtonSpeedActionPerformed

    private void jButtonSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoundActionPerformed
        principal.addComponentEmulatorJPanel("Wave Sensor", "Wave Sensor");
    }//GEN-LAST:event_jButtonSoundActionPerformed

    private void jButtonGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGPSActionPerformed
        principal.addComponentEmulatorJPanel("GPS Sensor", "GPS Sensor");
    }//GEN-LAST:event_jButtonGPSActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        principal.addComponentEmulatorJPanel("Water Sensor", "Water Sensor");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        principal.addComponentEmulatorJPanel("Wind Sensor", "Wind Sensor");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        principal.addComponentEmulatorJPanel("Alarm Actuator", "Alarm Actuator");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        principal.addComponentEmulatorJPanel("Fan Actuator", "Fan Actuator");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        principal.addComponentEmulatorJPanel("LED Actuator", "LED Actuator");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        principal.addComponentEmulatorJPanel("Motor Actuator", "Motor Actuator");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       principal.addComponentEmulatorJPanel("Smoke Sensor", "Smoke Sensor");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        principal.addComponentEmulatorJPanel("Motion Sensor", "Motion Sensor");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonGPS;
    private javax.swing.JButton jButtonHumedity;
    private javax.swing.JButton jButtonSound;
    private javax.swing.JButton jButtonSpeed;
    private javax.swing.JButton jButtonTemperature;
    private javax.swing.JPanel jPanelNodos;
    private javax.swing.JPanel jPanelNodosActuators1;
    private javax.swing.JScrollPane jScrollPaneActuators;
    private javax.swing.JScrollPane jScrollPaneSensors;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void addNewBotton() {
        JButton botton = new JButton("Botton" + indices);
        jPanelNodos.add(botton);
        indices++;
        jPanelNodos.updateUI();
    }

}
