package co.edu.usbbog.datan.niote.vista.paneles.principal;

import co.edu.usbbog.datan.niote.vista.Principal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Camilo y Roberth
 */
public class MainMenuJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form MenuPrincipalJPanel
     */
    public MainMenuJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButtonOpenProject = new javax.swing.JButton();
        jButtonSaveProject = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonDeleteVerque = new javax.swing.JButton();
        jButtonRunProject = new javax.swing.JButton();
        jButtonPauseSimulation = new javax.swing.JButton();

        jToolBar2.setBackground(new java.awt.Color(45, 45, 45));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton1.setBackground(new java.awt.Color(45, 45, 45));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/open_white_18dp.png"))); // NOI18N
        jButton1.setToolTipText("Abrir proyecto (COMBINACION)");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButtonOpenProject.setBackground(new java.awt.Color(45, 45, 45));
        jButtonOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/add_white_18dp.png"))); // NOI18N
        jButtonOpenProject.setToolTipText("Crear nuevo proyecto (COMBINACION)");
        jButtonOpenProject.setFocusable(false);
        jButtonOpenProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOpenProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenProjectActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonOpenProject);

        jButtonSaveProject.setBackground(new java.awt.Color(45, 45, 45));
        jButtonSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/save_white_18dp.png"))); // NOI18N
        jButtonSaveProject.setToolTipText("Guardar proyecto (COMBINACION)");
        jButtonSaveProject.setFocusable(false);
        jButtonSaveProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonSaveProject);
        jToolBar2.add(jSeparator1);

        jButtonDeleteVerque.setBackground(new java.awt.Color(45, 45, 45));
        jButtonDeleteVerque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/delete_white_18dp.png"))); // NOI18N
        jButtonDeleteVerque.setToolTipText("Borrar proyecto (COMBINACION)");
        jButtonDeleteVerque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonDeleteVerque.setFocusable(false);
        jButtonDeleteVerque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeleteVerque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteVerque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteVerqueActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonDeleteVerque);

        jButtonRunProject.setBackground(new java.awt.Color(45, 45, 45));
        jButtonRunProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/play_white_24dp.png"))); // NOI18N
        jButtonRunProject.setToolTipText("Ejecutar proyecto (COMBINACION)");
        jButtonRunProject.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRunProject.setFocusable(false);
        jButtonRunProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRunProject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRunProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunProjectActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonRunProject);

        jButtonPauseSimulation.setBackground(new java.awt.Color(45, 45, 45));
        jButtonPauseSimulation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/imagenes/menuprincipal/pause_white_18dp.png"))); // NOI18N
        jButtonPauseSimulation.setToolTipText("Pausar emulación (COMBINACION)");
        jButtonPauseSimulation.setFocusable(false);
        jButtonPauseSimulation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPauseSimulation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPauseSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseSimulationActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonPauseSimulation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteVerqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteVerqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteVerqueActionPerformed

    private void jButtonOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenProjectActionPerformed
        principal.goCreateProject();      // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOpenProjectActionPerformed

    private void jButtonRunProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunProjectActionPerformed
        principal.ejectProjectJTextArea();      // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRunProjectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            principal.openProjects();        // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(MainMenuJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPauseSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseSimulationActionPerformed
principal.stopEmulationProjectJTextArea();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPauseSimulationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDeleteVerque;
    private javax.swing.JButton jButtonOpenProject;
    private javax.swing.JButton jButtonPauseSimulation;
    private javax.swing.JButton jButtonRunProject;
    private javax.swing.JButton jButtonSaveProject;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

}
