/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista.paneles.principal;

import co.edu.usbbog.datan.niote.vista.Principal;

/**
 *
 * @author Camilo y Roberth
 */
public class OutputJPanel extends javax.swing.JPanel {

    private Principal principal;

    private int auxiliar = 0;
    private boolean realizado = false;
    hilo ejecutar = new hilo();
    boolean decision;

    /**
     * Creates new form OutputJPanel
     */
    public OutputJPanel(Principal principal) {
        this.principal = principal;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelOutput = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(47, 47, 47));

        jScrollPane2.setBackground(new java.awt.Color(47, 47, 47));
        jScrollPane2.setBorder(null);

        jPanelOutput.setBackground(new java.awt.Color(47, 47, 47));
        jPanelOutput.setForeground(new java.awt.Color(255, 255, 255));

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setBackground(new java.awt.Color(47, 47, 47));
        jTextAreaOutput.setColumns(70);
        jTextAreaOutput.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout jPanelOutputLayout = new javax.swing.GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanelOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

    public void ejectProject() {
        jTextAreaOutput.setText("Ejecutando proyecto...");
        /*if (realizado == false) {
            realizado = true;
            ejecutar.start();
        }*/
    }
    
    public void stopEmulation() {
        jTextAreaOutput.append("\nEmulación detenida.");
        /*if (realizado == false) {
            realizado = true;
            ejecutar.start();
        }*/
    }
      
    public void addNewComponentOnTextArea(String name) {
        jTextAreaOutput.append("\nHa agregado el componente: " + name);
    }

    private class hilo extends Thread {

        @Override
        public void run() {
            try {
                while (true) {
                    auxiliar++;
                    jTextAreaOutput.setText("Ejecutando proyecto...");
                    repaint();
                    switch (auxiliar) {
                        case 3:
                            jTextAreaOutput.append("\nCargando programa.");
                            break;
                        case 20:
                            jTextAreaOutput.append("\nCargando conexiones.");
                            break;
                        case 48:
                            jTextAreaOutput.append("\nCarga finalizada.");
                            break;
                        case 50:
                            jTextAreaOutput.append("\nSimulación iniciada.");

                            //    Principal principal = new Principal();
                            //  principal.setVisible(true);
                            //             System.out.println("s");
//                            principal.setLocationRelativeTo(PantallaDeCarga.this);
                            //dispose();
                            break;
                    }
                    Thread.sleep(100);
                }
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }
        }
    }

}
