/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista.paneles.principal;

import co.edu.usbbog.datan.niote.vista.Principal;
import javax.swing.table.DefaultTableModel;

/**
 * @author Camilo Andrés Díaz Gómez.
 * @version 1.0
 * @since August 2020.
 */
public class SimulatedDataJPanel extends javax.swing.JPanel {

    /**
     * Relations and variables
     */
    private Principal principal;
    DefaultTableModel dt = new DefaultTableModel();

    /**
     * Creates new form SimulatedDataJPanel
     */
    public SimulatedDataJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDates = new javax.swing.JTable();

        jTableDates.setBackground(new java.awt.Color(46, 46, 46));
        jTableDates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDates);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDates;
    // End of variables declaration//GEN-END:variables

    private void listDatesTittles(String tipoDeNodo, String nodo) {
        //  jTableDates.clear();
        if (tipoDeNodo.equals("Sensor")) {

            dt.addColumn("Hora");
            dt.addColumn("Segundo");
            dt.addColumn("Dato simulado");

        } else if (tipoDeNodo.equals("Actuador")) {
            dt.addColumn("Hora");
            dt.addColumn("Segundo");
            dt.addColumn("Dato recogido");
        } else if (tipoDeNodo.equals("Gateway")) {

        }

        // jTableDates = principal.getCbo().listaCorreo();
        Object[] filas = new Object[4];
        /*try {
            for (int i = 0; i < lista.size(); i++) {
                filas[0] = lista.get(i).getEmail();
                filas[1] = lista.get(i).getPassword();
                filas[2] = lista.get(i).getServer();
                filas[3] = lista.get(i).getUsuario().getCedula();
                dt.addRow(filas);
            }
            System.out.println("Cantidad de registros: " + lista.size());
        } catch (Exception e) {
            System.out.println("Error al consultar correos en la base de datos." + e.getMessage());
        }*/
        jTableDates.setModel(dt);
    }
}
