/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.recursos.pantallaPrincipal;

/**
 *
 * @author Camilo y Roberth
 */
public class DescripcionNodoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DescripcionNodo
     */
    public DescripcionNodoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelState = new javax.swing.JLabel();
        jLabelKind = new javax.swing.JLabel();
        jLabelMagnitude = new javax.swing.JLabel();
        jLabelFrecuency = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldState = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldMagnitude = new javax.swing.JTextField();
        jTextFieldFrecuency = new javax.swing.JTextField();
        jRadioButtonSensor = new javax.swing.JRadioButton();
        jRadioButtonActuator = new javax.swing.JRadioButton();
        jRadioButtonGateway = new javax.swing.JRadioButton();
        jScrollBarMain = new javax.swing.JScrollBar();

        setBackground(new java.awt.Color(45, 45, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Nombre:");
        add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID:");
        add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabelDescription.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("Descripcion:");
        add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabelState.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelState.setForeground(new java.awt.Color(255, 255, 255));
        jLabelState.setText("Estado:");
        add(jLabelState, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        jLabelKind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelKind.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKind.setText("Tipo");
        add(jLabelKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        jLabelMagnitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMagnitude.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMagnitude.setText("Magnitud");
        add(jLabelMagnitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jLabelFrecuency.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFrecuency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFrecuency.setText("Frecuencia");
        add(jLabelFrecuency, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        jTextFieldName.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, 323, -1));

        jTextFieldID.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldID.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 49, 323, -1));

        jTextFieldState.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldState.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 125, 323, -1));

        jTextFieldDescription.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldDescription.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 87, 323, -1));

        jTextFieldMagnitude.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldMagnitude.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldMagnitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 204, 324, -1));

        jTextFieldFrecuency.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldFrecuency.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldFrecuency, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 242, 324, -1));

        jRadioButtonSensor.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButtonSensor.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSensor.setText("Sensor");
        add(jRadioButtonSensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 163, -1, -1));

        jRadioButtonActuator.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButtonActuator.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonActuator.setText("Actuador");
        add(jRadioButtonActuator, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 163, -1, -1));

        jRadioButtonGateway.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButtonGateway.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonGateway.setText("Gateway");
        add(jRadioButtonGateway, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 163, -1, -1));
        add(jScrollBarMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 250));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFrecuency;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelKind;
    private javax.swing.JLabel jLabelMagnitude;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JRadioButton jRadioButtonActuator;
    private javax.swing.JRadioButton jRadioButtonGateway;
    private javax.swing.JRadioButton jRadioButtonSensor;
    private javax.swing.JScrollBar jScrollBarMain;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldFrecuency;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldMagnitude;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldState;
    // End of variables declaration//GEN-END:variables


}
