/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.recursos.pantallaPrincipal;

/**
 *
 * @author Camilo y Roberth
 */
public class DescripcionNodoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DescripcionNodo
     */
    public DescripcionNodoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        setBackground(new java.awt.Color(45, 45, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Magnitud");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Frecuencia");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        jTextField1.setBackground(new java.awt.Color(45, 45, 45));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, 323, -1));

        jTextField2.setBackground(new java.awt.Color(45, 45, 45));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 49, 323, -1));

        jTextField3.setBackground(new java.awt.Color(45, 45, 45));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 125, 323, -1));

        jTextField5.setBackground(new java.awt.Color(45, 45, 45));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 87, 323, -1));

        jTextField6.setBackground(new java.awt.Color(45, 45, 45));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 204, 324, -1));

        jTextField7.setBackground(new java.awt.Color(45, 45, 45));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 242, 324, -1));

        jRadioButton1.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Sensor");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 163, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Actuador");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 163, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(45, 45, 45));
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Gateway");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 163, -1, -1));
        add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 250));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables


}
