/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.recursos.pantallaPrincipal;

import co.edu.usbbog.datan.niote.vista.AgregarNodoIoTJPanel;
import co.edu.usbbog.datan.niote.vista.ComunicacionLogica;
import co.edu.usbbog.datan.niote.vista.Navegacion;
import co.edu.usbbog.datan.niote.vista.Principal;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFileChooser;

/**
 *
 * @author Camilo y Roberth
 */
public class PaletaNodosDinamicosJPanel extends javax.swing.JPanel {

    private List<JButton> nodes;
    private Integer indices;
    private AgregarNodoIoTJPanel agregarNodoIoTJPanel;
    private Navegacion navegacion;
    private ComunicacionLogica comunicacionLogica;
    /**
     * Creates new form PaletaNodosDinamicosJPanel
     */
    public PaletaNodosDinamicosJPanel() {
        this.comunicacionLogica = new ComunicacionLogica();
        this.navegacion=new Navegacion();
        nodes = new ArrayList<>();
        indices = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelNodos = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 27, 27));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNodos.setBackground(new java.awt.Color(61, 61, 61));
        jPanelNodos.setLayout(new java.awt.GridLayout(0, 3));

        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/paletaNodos/HumidityIcon_35.45.png"))); // NOI18N
        jButton2.setText("Humedad");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelNodos.add(jButton2);

        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/paletaNodos/TemperatureIcon_36.59.png"))); // NOI18N
        jButton3.setText("Temperatura");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jPanelNodos.add(jButton3);

        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/paletaNodos/SpeedIcon_75.38.png"))); // NOI18N
        jButton5.setText("Velocidad");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jPanelNodos.add(jButton5);

        jButton6.setForeground(new java.awt.Color(240, 240, 240));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/paletaNodos/SoundWhiteIcon_42.42.png"))); // NOI18N
        jButton6.setText("Sonido");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jPanelNodos.add(jButton6);

        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/paletaNodos/GPSIcon_38.59.png"))); // NOI18N
        jButton4.setText("GPS");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jPanelNodos.add(jButton4);

        jScrollPane1.setViewportView(jPanelNodos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, -1, 250));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_add_white_18dp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 30, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        navegacion.goAddNewNode();
        File imegen = navegacion.searchNewImagen();
//        JButton jButoon=new JButton("Boton con imagen", imegen.);
        addNewBotton();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        comunicacionLogica.agregarComponente("Agua", 1);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanelNodos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addNewBotton() {
        JButton botton = new JButton("Botton" + indices);
        jPanelNodos.add(botton);
        indices++;
        jPanelNodos.updateUI();
    }

}
