/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

import co.edu.usbbog.datan.niote.vista.media.TextPrompt;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo y Roberth
 * @version 1.0
 */
public class CrearProyectoJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form InicioJPanel
     */
    public CrearProyectoJPanel(Principal principal) {
        this.principal = principal;
        homePreviousTexts();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloCreacion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jButtonBuscarNuevaUbicacion = new javax.swing.JButton();
        jTextFieldNombreDelProyecto = new javax.swing.JTextField();
        jButtonCrearProyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelUbicacion1 = new javax.swing.JLabel();
        jTextFieldUbicacion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(27, 27, 27));

        jLabelTituloCreacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTituloCreacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloCreacion.setText("Creacion de nuevo proyecto");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");

        jLabelUbicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUbicacion.setText("Ubicacion:");

        jButtonBuscarNuevaUbicacion.setBackground(new java.awt.Color(66, 66, 66));
        jButtonBuscarNuevaUbicacion.setText("Buscar nueva ubicacion");
        jButtonBuscarNuevaUbicacion.setBorderPainted(false);
        jButtonBuscarNuevaUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBuscarNuevaUbicacion.setDefaultCapable(false);
        jButtonBuscarNuevaUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNuevaUbicacionActionPerformed(evt);
            }
        });

        jTextFieldNombreDelProyecto.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldNombreDelProyecto.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCrearProyecto.setBackground(new java.awt.Color(66, 66, 66));
        jButtonCrearProyecto.setText("Crear proyecto");
        jButtonCrearProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearProyectoActionPerformed(evt);
            }
        });

        jTextAreaDescripcion.setBackground(new java.awt.Color(45, 45, 45));
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setBorder(null);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabelUbicacion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUbicacion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUbicacion1.setText("Descripción");

        jTextFieldUbicacion.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUbicacion.setText("C:\\Users\\Camilo y Roberth\\Documents\\NIOTE_Projects");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCrearProyecto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUbicacion1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUbicacion)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabelTituloCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNombreDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUbicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarNuevaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTituloCreacion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombreDelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUbicacion)
                    .addComponent(jButtonBuscarNuevaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabelUbicacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearProyecto)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarNuevaUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNuevaUbicacionActionPerformed
        searchNewLocation();
    }//GEN-LAST:event_jButtonBuscarNuevaUbicacionActionPerformed

    private void jButtonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearProyectoActionPerformed
        createProject();
        goToEmulation();
    }//GEN-LAST:event_jButtonCrearProyectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarNuevaUbicacion;
    private javax.swing.JButton jButtonCrearProyecto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTituloCreacion;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JLabel jLabelUbicacion1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldNombreDelProyecto;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to go to the emulation screen
     */
    private void goToEmulation() {
        jTextFieldNombreDelProyecto.setBackground(Color.GRAY);
        jTextFieldNombreDelProyecto.setForeground(Color.GREEN);
// principal.irAEm(this);
    }

    /**
     * Method to create new project with the entered data
     */
    private void createProject() {
        Boolean validacion = validationEntereData();
        if (validacion = true) {
            String nombre = jTextFieldNombreDelProyecto.getText();
            String descripcion = jTextAreaDescripcion.getText();

            principal.crearRed(nombre, nombre, descripcion);
            principal.arbolProyectosJPanel.joinedProjects(nombre);
            keepRed();
            principal.cerrarVentana();
        }
    }

    /**
     * Method the new project will be saved in the chosen path
     */
    private void keepRed() {
        String ruta = jTextFieldUbicacion.getText();
        // System.out.println(ruta);
        //System.out.println(jTextFieldNombreDelProyecto.getText() + " difsoifndsiofnsf");
        String nombreArchivo = jTextFieldNombreDelProyecto.getText();
        System.out.println(this.principal.getGestionRed().guardarRed(ruta, nombreArchivo));
    }

    private void homePreviousTexts() {
//        TextPrompt textoNombre = new TextPrompt("Nombre del nuevo proyecto", jTextFieldNombreDelProyecto);
        //       TextPrompt textoDescripcion = new TextPrompt("Descripción del nuevo proyecto", jTextAreaDescripcion);
    }

    /**
     * Method to validate that the project name and description boxes have text
     *
     * @return True if it have text, false if it don't have it
     */
    private boolean validationEntereData() {
        String comparableProjectName = "javax.swing.JTextField[,89,57,309x20,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=com.sun.java.swing.plaf.windows.XPStyle$XPFillBorder@69d11f90,flags=296,maximumSize=,minimumSize=,preferredSize=,caretColor=javax.swing.plaf.ColorUIResource[r=0,g=0,b=0],disabledTextColor=javax.swing.plaf.ColorUIResource[r=109,g=109,b=109],editable=true,margin=javax.swing.plaf.InsetsUIResource[top=2,left=2,bottom=2,right=2],selectedTextColor=javax.swing.plaf.ColorUIResource[r=255,g=255,b=255],selectionColor=javax.swing.plaf.ColorUIResource[r=0,g=120,b=215],columns=0,columnWidth=0,command=,horizontalAlignment=LEADING]";
        String comparableDescription = "javax.swing.JTextArea[,0,0,537x111,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=296,maximumSize=,minimumSize=,preferredSize=,caretColor=javax.swing.plaf.ColorUIResource[r=0,g=0,b=0],disabledTextColor=javax.swing.plaf.ColorUIResource[r=109,g=109,b=109],editable=true,margin=javax.swing.plaf.InsetsUIResource[top=2,left=2,bottom=2,right=2],selectedTextColor=javax.swing.plaf.ColorUIResource[r=255,g=255,b=255],selectionColor=javax.swing.plaf.ColorUIResource[r=0,g=120,b=215],colums=20,columWidth=8,rows=5,rowHeight=14,word=false,wrap=false]";
        //System.out.println(jTextFieldNombreDelProyecto+" 222222");
        //      System.out.println(jTextAreaDescripcion+" 333");
        if (jTextFieldNombreDelProyecto.getText() == null || jTextFieldNombreDelProyecto.getText() == "" || jTextFieldNombreDelProyecto.getText() == comparableProjectName) {
            if (jTextAreaDescripcion.getText() == null || jTextAreaDescripcion.getText() == "" || jTextAreaDescripcion.getText() == comparableDescription) {
                //   Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
                JOptionPane.showMessageDialog(this, "Tiene un campo donde el valor no es valido o esta vacio", "Error al agregar la  nueva aeronave", JOptionPane.INFORMATION_MESSAGE);

                JOptionPane.showMessageDialog(null, "Hace falta ingresar la descripcion del proyecto");
                return false;
            }
            JOptionPane.showMessageDialog(null, "Hace falta ingresar el nombre del proyecto");
            return false;
        } else {
            return true;
        }
    }

    /**
     *
     */
    private void searchNewLocation() {
        JFileChooser chooser;
        String choosertitle = null;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//            System.out.println("getCurrentDirectory(): "
//                    + chooser.getCurrentDirectory());
//            System.out.println("getSelectedFile() : "
//                    + chooser.getSelectedFile());
            jTextFieldUbicacion.setText(String.valueOf(chooser.getSelectedFile()));
        } else {
            System.out.println("No Selection ");
        }
    }
}
