/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

import co.edu.usbbog.datan.niote.controlador.logica.GestionRed;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Camilo Andrés Díaz Gómez.
 * @version 1.0
 * @since April 2020.
 */
public class CreateProjectJPanel extends javax.swing.JPanel {

    /**
     * Relations
     */
    private Principal principal;

    /**
     * Creates new form InicioJPanel
     */
    public CreateProjectJPanel(Principal principal) {
        this.principal = principal;
        homePreviousTexts();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitleCreation = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelLocation = new javax.swing.JLabel();
        jButtonSearchNewLocation = new javax.swing.JButton();
        jTextFieldProjectName = new javax.swing.JTextField();
        jButtonCreateProject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabelDescription = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();

        setBackground(new java.awt.Color(27, 27, 27));

        jLabelTitleCreation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTitleCreation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleCreation.setText("Creacion de nuevo proyecto");

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Nombre:");

        jLabelLocation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLocation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLocation.setText("Ubicacion:");

        jButtonSearchNewLocation.setBackground(new java.awt.Color(66, 66, 66));
        jButtonSearchNewLocation.setText("Buscar nueva ubicacion");
        jButtonSearchNewLocation.setBorderPainted(false);
        jButtonSearchNewLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSearchNewLocation.setDefaultCapable(false);
        jButtonSearchNewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchNewLocationActionPerformed(evt);
            }
        });

        jTextFieldProjectName.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldProjectName.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCreateProject.setBackground(new java.awt.Color(66, 66, 66));
        jButtonCreateProject.setText("Crear proyecto");
        jButtonCreateProject.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateProjectActionPerformed(evt);
            }
        });

        jTextAreaDescription.setBackground(new java.awt.Color(45, 45, 45));
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextAreaDescription.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setBorder(null);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabelDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("Descripción");

        jTextFieldLocation.setBackground(new java.awt.Color(45, 45, 45));
        jTextFieldLocation.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLocation.setText(principal.obteinDocumentsPath()+"\\Niote Projects");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreateProject))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDescription)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLocation)
                            .addComponent(jLabelName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabelTitleCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchNewLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitleCreation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocation)
                    .addComponent(jButtonSearchNewLocation)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreateProject)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchNewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchNewLocationActionPerformed
        searchNewLocation();
    }//GEN-LAST:event_jButtonSearchNewLocationActionPerformed

    private void jButtonCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateProjectActionPerformed
        createProject();
    }//GEN-LAST:event_jButtonCreateProjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateProject;
    private javax.swing.JButton jButtonSearchNewLocation;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitleCreation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldProjectName;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to create new project with the entered data.
     */
    private void createProject() {
//        if (validationEntereData() == true) {
        String nombre = jTextFieldProjectName.getText();
        String descripcion = jTextAreaDescription.getText();

        GestionRed gRedCreada = principal.createNetwork(nombre, nombre, descripcion);
        principal.projectsTreeJPanel.joinedProjects(nombre, gRedCreada);
        //  principal.arbolProyectosJPanel.joinedProjects(nombre);
        keepRed();
        principal.closeWindow();
//        }
    }

    /**
     * Method the new project will be saved in the chosen path.
     */
    private void keepRed() {
        String ruta = jTextFieldLocation.getText();
        String nombreArchivo = jTextFieldProjectName.getText();
        System.out.println(this.principal.getGestionRed().guardarRed(ruta, nombreArchivo));
    }

    private void homePreviousTexts() {
//        TextPrompt textoNombre = new TextPrompt("Nombre del nuevo proyecto", jTextFieldNombreDelProyecto);
        //       TextPrompt textoDescripcion = new TextPrompt("Descripción del nuevo proyecto", jTextAreaDescripcion);
    }

    /**
     * Method to find a new location where the user will save the project.
     */
    private void searchNewLocation() {
        JFileChooser chooser;
        String choosertitle = null;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextFieldLocation.setText(String.valueOf(chooser.getSelectedFile()));
        } else {
            System.out.println("No Selection");
        }
    }

    private boolean validationEntereData() {
        String name = jTextFieldProjectName.getText();
        String path = jTextFieldLocation.getText();
        String description = jTextAreaDescription.getText();
        if (name.equals("")) {
            if (path.equals("")) {
                if (description.equals("")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Hace falta ingresar la descripción del proyecto.", "Error al crear el proyecto", HEIGHT);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hace falta ingresar la dirección del proyecto.", "Error al crear el proyecto", HEIGHT);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hace falta ingresar el nombre del proyecto.", "Error al crear el proyecto", HEIGHT);
            return false;
        }
    }
}
