/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

import co.edu.usbbog.datan.niote.recursos.pantallaDeEmulacion.ComponentController;
import javax.swing.DefaultListModel;

/**
 *
 * @author contr
 */
public class EmulacionJPanel extends javax.swing.JPanel {
    
    private ComunicacionLogica comunicacionLogica;
    
//    private ComponentController controladorComponentes;
//    private DefaultListModel lista = new DefaultListModel();


    /**
     * Creates new form panelJPanel
     */
    public EmulacionJPanel() {
        initComponents();
        //crea nueva instancia e inicia parametros
//        controladorComponentes = new ComponentController(this.panelContenedor, this.lista);
        //agrega ListModel a JList
//        listaComponentesJList.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBackground(new java.awt.Color(61, 61, 61));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
    
//    public void agregarComponente(String nombre, int id) {
//        controladorComponentes.nuevoComponente(nombre, id);
//    }
}
