/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

/**
 *
 * @author contr
 */
public class EmulationJPanel extends javax.swing.JPanel {

//    private ComponentController controladorComponentes;
//    private DefaultListModel lista = new DefaultListModel();
    private Principal principal;

    /**
     * Creates new form panelJPanel
     */
    public EmulationJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
        //crea nueva instancia e inicia parametros
//        controladorComponentes = new ComponentController(this.panelContenedor, this.lista);
        //agrega ListModel a JList
//        listaComponentesJList.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemInfComponent = new javax.swing.JMenuItem();
        jMenuItemSimulatedData = new javax.swing.JMenuItem();

        jMenuItemInfComponent.setText("Ver informacion del componente");
        jMenuItemInfComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfComponentActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemInfComponent);

        jMenuItemSimulatedData.setText("Ver datos simulados");
        jMenuItemSimulatedData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSimulatedDataActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemSimulatedData);

        setBackground(new java.awt.Color(61, 61, 61));
        setComponentPopupMenu(jPopupMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInfComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfComponentActionPerformed
        if (true) {
            principal.goInfComponent();
        }
    }//GEN-LAST:event_jMenuItemInfComponentActionPerformed

    private void jMenuItemSimulatedDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSimulatedDataActionPerformed
        principal.goSimulatedData();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSimulatedDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItemInfComponent;
    private javax.swing.JMenuItem jMenuItemSimulatedData;
    private javax.swing.JPopupMenu jPopupMenu;
    // End of variables declaration//GEN-END:variables

}
