/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

import co.edu.usbbog.datan.niote.controlador.logica.ValidacionesSistema;

/**
 *
 * @author Camilo y Roberth
 */
public class PantallaDeCargaJPanel extends javax.swing.JPanel {

    //Relacones
    private Principal principal;

    ValidacionesSistema validaciones;

    Boolean valorTomado;

    /**
     * Creates new form PantallaDeCargaJPanel
     */
    public PantallaDeCargaJPanel(Principal principal) {

        this.principal = principal;
        this.valorTomado = false;
        //    this.validaciones = new ValidacionesSistema();
//        setProgresoMax(100);
//        this.principal.setUndecorated(true);
        validacionesMetodo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCarga = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabelProgreso = new javax.swing.JLabel();

        jPanelCarga.setBackground(new java.awt.Color(27, 27, 27));
        jPanelCarga.setForeground(new java.awt.Color(33, 33, 33));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/LogoNIOTE.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCargaLayout = new javax.swing.GroupLayout(jPanelCarga);
        jPanelCarga.setLayout(jPanelCargaLayout);
        jPanelCargaLayout.setHorizontalGroup(
            jPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelProgreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelCargaLayout.setVerticalGroup(
            jPanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCargaLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabelProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Boolean getValorTomado() {
        return valorTomado;
    }

    public void setValorTomado(Boolean valorTomado) {
        this.valorTomado = valorTomado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelProgreso;
    private javax.swing.JPanel jPanelCarga;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    public boolean validacionesMetodo() {
//        principal.cerrarVentana();
//        jLabelProgreso.setText("Paso");
//        return validaciones.estaConfiguradoElSistema();
        return true;
    }

    public void setProgresoMax(int maxProgress) {
        jProgressBar1.setMaximum(maxProgress);
    }

    public void setProgreso(int progress) {
        final int progreso = progress;
        jProgressBar1.setValue(progreso);
    }

    public void setProgreso(String message, int progress) {
        final int progreso = progress;
        final String theMessage = message;
        setProgreso(progress);
        jProgressBar1.setValue(progreso);
        setMessage(theMessage);
    }

    private void setMessage(String message) {
        if (message == null) {
            message = "";
            jProgressBar1.setStringPainted(false);
        } else {
            jProgressBar1.setStringPainted(true);
        }
        jProgressBar1.setString(message);
    }

    public void velocidadDeCarga() {
        for (int i = 0; i <= 100; i++) {
            for (long j = 0; j < 100000; ++j)//modifica el numero segun la velidad q desees
            {
                String poop = " " + (j + i);
            }
            setProgreso("" + i, i);  // si quieres q muestre los numeros y un mensaje
            //setProgreso(i);        //si no quieres q muestre nada, solo la barra
        }
    }

}
