/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

//Packet Tracer ver tutoriales
//IconElectronics

/*
Relaciones
 */
// Logica
import co.edu.usbbog.datan.niote.controlador.logica.Emulador;
import co.edu.usbbog.datan.niote.controlador.logica.GestionRed;
import co.edu.usbbog.datan.niote.controlador.logica.ValidacionesSistema;
import co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.ArbolProyectosJPanel;

//Emulador (Grafico)
import co.edu.usbbog.datan.niote.vista.media.Graficar;
import co.edu.usbbog.datan.niote.vista.media.Grafos;
import co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosIoTJPanel;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;

//Files
import java.io.File;

import java.nio.file.Files;
import javax.swing.JFileChooser;

//Excepciones 
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

//Explorador de archivos
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;

/**
 *
 * @author Camilo Andres Diaz Gomez
 * @author Jhonatan Villareal
 * @author Juan Esteban Contreras Diaz
 */
public class Principal extends JFrame {

    //Relacion Logica
    private GestionRed gestionRed;
    private ValidacionesSistema validacionesSistema;
    public Navegacion navegacion;
    private Emulador emulador;

    //relaciones vista
    private Terminal terminal;

    /*
    Componentes 
     */
    private int tope = 0;//acumulado 
    private int end; // nultimo nodo
    private int start;
    int n = 0, nn = 0, id, id2;
    private int aristM;
    WindowDialog ventanaDialog;

    PantallaDeCarga jP;
//    PantallaDeCargaJPanel pantallaDeCargaJPanel;

    CrearProyectoJPanel crearProyectoJPanel;
    EmulacionJPanel emulacionJPanel;
    AgregarNodoIoTJPanel agregarNodoIoTJPanel;
    PaletaNodosIoTJPanel paletaSensoresJPanel;
    ArbolProyectosJPanel arbolProyectosJPanel;
    NotificarErrorJPanel notificarErrorJPanel;
    SobreNosotrosJPanel sobreNosotrosJPanel;

    private Dimension dim;

    /**
     * Creates new form Principal
     */
    public Principal() {

        setTitle("NIOTE");

        setIconImage(new ImageIcon(getClass().getResource("../vista/media/IconNIOTE.png")).getImage());
        setName("pricipalJFrame");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        //  pack();
        //      setLocationRelativeTo(null);

        /*
        Logic relationships
         */
        //  this.pantallaDeCargaJPanel = new PantallaDeCargaJPanel(this);
        this.validacionesSistema = new ValidacionesSistema();
        this.emulador = new Emulador(this);
        this.navegacion = new Navegacion();
        // Method to mark and unmark the necessary CheckBox
        // checkBoxValidation();
        // Verification of requirements
        //    if (validation() == true) {
        //  jP.dispose();
        // Creation of root folder (Where they are saved by default)
        crearCarpeta();
        // Initialization for emulation (graphical environment)
        Graficar paint = new Graficar();
        Grafos trees = new Grafos();
        Graficar graph = new Graficar();
        // iniciar();
        // Start
        initComponents();
        //         jP.dispose();

        //Pack the window
        this.pack();
        // Center window
        this.setLocationRelativeTo(null);
        // Maximize the window in its maximum size adapting it to the screen
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//            validarBotonesClickeados();
        //      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        arbolProyectosJPanel1 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.ArbolProyectosJPanel();
        paletaNodosDinamicosJPanel2 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosDinamicosJPanel();
        descripcionNodoJPanel2 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.DescripcionNodoJPanel();
        menuPrincipalJPanel1 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.MenuPrincipalJPanel();
        emulacionJPanel2 = new co.edu.usbbog.datan.niote.vista.EmulacionJPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchive = new javax.swing.JMenu();
        jMenuItemNewProject = new javax.swing.JMenuItem();
        jMenuItemOpenProject = new javax.swing.JMenuItem();
        jMenuItemCloseProject = new javax.swing.JMenuItem();
        jMenuItemCloseAllProjects = new javax.swing.JMenuItem();
        jMenuExport = new javax.swing.JMenu();
        jMenuItemExportToRar = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuExecute = new javax.swing.JMenu();
        jMenuItemRun = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemDocumentation = new javax.swing.JMenuItem();
        jMenuItemReportError = new javax.swing.JMenuItem();
        jMenuItemSearchUpdate = new javax.swing.JMenuItem();
        jMenuItemAboutUs = new javax.swing.JMenuItem();
        jMenuWindows = new javax.swing.JMenu();
        jMenuItemWindowsConfiguration = new javax.swing.JMenuItem();
        jMenuLanguage = new javax.swing.JMenu();
        jCheckBoxMenuItemSpanishLanguage = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEnglishLanguage = new javax.swing.JCheckBoxMenuItem();
        jMenuThemes = new javax.swing.JMenu();
        jCheckBoxMenuItemLightTheme = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDarkTheme = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 109, 0));

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));
        jPanel2.setForeground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout emulacionJPanel2Layout = new javax.swing.GroupLayout(emulacionJPanel2);
        emulacionJPanel2.setLayout(emulacionJPanel2Layout);
        emulacionJPanel2Layout.setHorizontalGroup(
            emulacionJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        emulacionJPanel2Layout.setVerticalGroup(
            emulacionJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(arbolProyectosJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emulacionJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionNodoJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paletaNodosDinamicosJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuPrincipalJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menuPrincipalJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arbolProyectosJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(paletaNodosDinamicosJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcionNodoJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(emulacionJPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar.setBackground(new java.awt.Color(27, 27, 27));
        jMenuBar.setBorder(null);

        jMenuArchive.setBackground(new java.awt.Color(45, 45, 45));
        jMenuArchive.setText("Archivo");

        jMenuItemNewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/crearproyectox1_18.png"))); // NOI18N
        jMenuItemNewProject.setText("Nuevo proyecto");
        jMenuItemNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewProjectActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemNewProject);

        jMenuItemOpenProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/Openx1_18.png"))); // NOI18N
        jMenuItemOpenProject.setText("Abrir proyecto");
        jMenuItemOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenProjectActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemOpenProject);

        jMenuItemCloseProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCloseProject.setBackground(new java.awt.Color(45, 45, 45));
        jMenuItemCloseProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/cerrarx1_18.png"))); // NOI18N
        jMenuItemCloseProject.setText("Cerrar proyecto");
        jMenuItemCloseProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseProjectActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemCloseProject);

        jMenuItemCloseAllProjects.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCloseAllProjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/cerrarx1_18.png"))); // NOI18N
        jMenuItemCloseAllProjects.setText("Cerrar todos los proyectos");
        jMenuArchive.add(jMenuItemCloseAllProjects);

        jMenuExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/Exportx1_18.png"))); // NOI18N
        jMenuExport.setText("Exportar");

        jMenuItemExportToRar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/rarx1_18.png"))); // NOI18N
        jMenuItemExportToRar.setText("a .rar");
        jMenuExport.add(jMenuItemExportToRar);

        jMenuArchive.add(jMenuExport);

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/Exitx1_18.png"))); // NOI18N
        jMenuItemExit.setText("Salir");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemExit);

        jMenuBar.add(jMenuArchive);
        jMenuArchive.getAccessibleContext().setAccessibleDescription("");

        jMenuEdit.setText("Editar");

        jMenuItem4.setText("Borrar proyecto");
        jMenuEdit.add(jMenuItem4);

        jMenuBar.add(jMenuEdit);

        jMenuExecute.setText("Ejecutar");

        jMenuItemRun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/Executex1_18.png"))); // NOI18N
        jMenuItemRun.setText("Ejecutar");
        jMenuItemRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRunActionPerformed(evt);
            }
        });
        jMenuExecute.add(jMenuItemRun);

        jMenuBar.add(jMenuExecute);

        jMenuHelp.setText("Ayuda");

        jMenuItemDocumentation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/documentacionx1_18.png"))); // NOI18N
        jMenuItemDocumentation.setText("Documentacion (Proximamente...)");
        jMenuHelp.add(jMenuItemDocumentation);

        jMenuItemReportError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/BugNotificationx1_18dp.png"))); // NOI18N
        jMenuItemReportError.setText("Reportar error");
        jMenuItemReportError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportErrorActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemReportError);

        jMenuItemSearchUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/Updatex1_18.png"))); // NOI18N
        jMenuItemSearchUpdate.setText("Buscar actualizaciones");
        jMenuHelp.add(jMenuItemSearchUpdate);

        jMenuItemAboutUs.setText("Sobre nosotros");
        jMenuItemAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutUsActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAboutUs);

        jMenuBar.add(jMenuHelp);

        jMenuWindows.setText("Ventana");

        jMenuItemWindowsConfiguration.setText("Configuración de la ventana");
        jMenuWindows.add(jMenuItemWindowsConfiguration);

        jMenuLanguage.setText("Idioma");

        jCheckBoxMenuItemSpanishLanguage.setText("Español");
        jMenuLanguage.add(jCheckBoxMenuItemSpanishLanguage);

        jCheckBoxMenuItemEnglishLanguage.setText("English");
        jMenuLanguage.add(jCheckBoxMenuItemEnglishLanguage);

        jMenuWindows.add(jMenuLanguage);

        jMenuThemes.setText("Temas");

        jCheckBoxMenuItemLightTheme.setText("Claro");
        jMenuThemes.add(jCheckBoxMenuItemLightTheme);

        jCheckBoxMenuItemDarkTheme.setSelected(true);
        jCheckBoxMenuItemDarkTheme.setText("Oscuro");
        jMenuThemes.add(jCheckBoxMenuItemDarkTheme);

        jMenuWindows.add(jMenuThemes);

        jMenuBar.add(jMenuWindows);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewProjectActionPerformed
        navegacion.goCreateProject();
    }//GEN-LAST:event_jMenuItemNewProjectActionPerformed

    private void jMenuItemOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenProjectActionPerformed
        navegacion.openProjects();
    }//GEN-LAST:event_jMenuItemOpenProjectActionPerformed

    private void jMenuItemAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutUsActionPerformed
        navegacion.goAboutUs();
    }//GEN-LAST:event_jMenuItemAboutUsActionPerformed

    private void jMenuItemReportErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportErrorActionPerformed
        navegacion.goReportError();
    }//GEN-LAST:event_jMenuItemReportErrorActionPerformed

    private void jMenuItemRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRunActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemCloseProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseProjectActionPerformed
        arbolProyectosJPanel1.deleteProjects();
    }//GEN-LAST:event_jMenuItemCloseProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public GestionRed getGestionRed() {
        return gestionRed;
    }

    public Terminal getTerminal() {
        return terminal;
    }

    public ValidacionesSistema getValidacionesSistema() {
        return validacionesSistema;
    }

    public Emulador getEmulador() {
        return emulador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.ArbolProyectosJPanel arbolProyectosJPanel1;
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.DescripcionNodoJPanel descripcionNodoJPanel2;
    private co.edu.usbbog.datan.niote.vista.EmulacionJPanel emulacionJPanel2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDarkTheme;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEnglishLanguage;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemLightTheme;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemSpanishLanguage;
    private javax.swing.JMenu jMenuArchive;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuExecute;
    private javax.swing.JMenu jMenuExport;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAboutUs;
    private javax.swing.JMenuItem jMenuItemCloseAllProjects;
    private javax.swing.JMenuItem jMenuItemCloseProject;
    private javax.swing.JMenuItem jMenuItemDocumentation;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemExportToRar;
    private javax.swing.JMenuItem jMenuItemNewProject;
    private javax.swing.JMenuItem jMenuItemOpenProject;
    private javax.swing.JMenuItem jMenuItemReportError;
    private javax.swing.JMenuItem jMenuItemRun;
    private javax.swing.JMenuItem jMenuItemSearchUpdate;
    private javax.swing.JMenuItem jMenuItemWindowsConfiguration;
    private javax.swing.JMenu jMenuLanguage;
    private javax.swing.JMenu jMenuThemes;
    private javax.swing.JMenu jMenuWindows;
    private javax.swing.JPanel jPanel2;
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.MenuPrincipalJPanel menuPrincipalJPanel1;
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosDinamicosJPanel paletaNodosDinamicosJPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // The search windows in the documents will come out with the customization of windows
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    void iniciar() {

        if (iniciarCarga(this) == false) {
            //Pack the window            
            this.pack();

            // Center window
            this.setLocationRelativeTo(null);

            // Maximize the window in its maximum size adapting it to the screen
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            // remove(jP);

        } else {
            System.out.println("no");
        }

    }

    // Navigation from start
    public Boolean iniciarCarga(JFrame jFrame) {
        // remove(jFrame);
        jP = new PantallaDeCarga(this);
        jP.setVisible(true);
        //  add(jP);
        pack();
        setLocationRelativeTo(null);
        return jP.decision;
    }

    /**
     * Method to create main emulator folder in documents
     */
    private void crearCarpeta() {
        String ubicacion = "C:\\Users\\Camilo y Roberth\\Documents\\NIOTE_Projects";
        File carpeta = new File(ubicacion);
        if (carpeta.mkdirs()) {
        } else {
            carpeta.mkdirs();
        }
    }

    /**
     * Method to create a new network
     *
     * @param id of the network
     * @param name of the network
     * @param description of the network
     * @return True if the network was created or False if not
     */
    protected boolean crearRed(String id, String name, String description) {
        this.gestionRed = new GestionRed(id, name, description);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Method to load a previously created network
     *
     * @param route of the network
     * @param fileName of the project
     * @return True if the network was loaded or False if not
     */
    protected boolean cargarRed(String route, String fileName) {
        this.gestionRed = new GestionRed(route, fileName);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Method to validate the clicked key or key combination
     */
    /* private void validarBotonesClickeados() {
        java.awt.event.KeyEvent evt = null;
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_F5) {
            jButtonRun.doClick();
        }
    }*/
    private boolean customizar() {
        if (jCheckBoxMenuItemSpanishLanguage.isEnabled()) {
            if (jCheckBoxMenuItemEnglishLanguage.isEnabled()) {
                jCheckBoxMenuItemSpanishLanguage.isSelected();
            }
            return false;
        } else {
            return true;
        }
    }

    /*  private boolean validation() {
        // Show loading window
        navegacion.chargingScreen();
        return validacionesSistema.getValidacionPantalla();
    }*/
}
