#!/bin/bash
# chkconfig: 345 99 01
# description: programa que habilita el gateway como AP

ifconfig eth0 up
sleep 1s
dhclient eth0
sleep 1s
modprobe -r dhd
sleep 1s
modprobe dhd op_mode=2
sleep 1s
ifconfig wlan0 192.168.1.2 up
sleep 1s
dnsmasq -C /etc/dnsmasq.conf
sleep 1s
sysctl net.ipv4.ip_forward=1
iptables --flush
iptables -t nat --flush
iptables --delete-chain
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i wlan0 -j ACCEPT
sleep 1s
hostapd /etc/hostapd/hostapd.conf -B
sleep 1s
exit

