CREATE DATABASE `niote2`;

USE niote2;

CREATE TABLE `presion` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `presion_promedio` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `precipitacion` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `precipitacion_promedio` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `humedad` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `humedad_promedios` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `temperatura` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `temperatura_promedio` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservado` varchar(15) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL,
  `DescripcionSensor` varchar(80) DEFAULT NULL,
  `UnidadMedida` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cruce_humedad_precipitacion` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(20) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservadoVr1` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr1` varchar(20) DEFAULT NULL,
  `ValorObservadoVr2` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr2` varchar(20) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cruce_presion_temperatura` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(20) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservadoVr1` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr1` varchar(20) DEFAULT NULL,
  `ValorObservadoVr2` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr2` varchar(20) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cruces_h_p_p_t` (
  `CodigoEstacion` varchar(20) DEFAULT NULL,
  `CodigoSensor` varchar(20) DEFAULT NULL,
  `FechaObservacion` varchar(80) DEFAULT NULL,
  `Dia` varchar(45) DEFAULT NULL,
  `Mes` varchar(45) DEFAULT NULL,
  `Anio` varchar(45) DEFAULT NULL,
  `Fecha` varchar(20) DEFAULT NULL,
  `Hora` varchar(45) DEFAULT NULL,
  `ValorObservadoVr1` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr1` varchar(20) DEFAULT NULL,
  `ValorObservadoVr2` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr2` varchar(20) DEFAULT NULL,
  `ValorObservadoVr3` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr3` varchar(20) DEFAULT NULL,
  `ValorObservadoVr4` varchar(15) DEFAULT NULL,
  `UnidadMedidaVr4` varchar(20) DEFAULT NULL,
  `NombreEstacion` varchar(80) DEFAULT NULL,
  `Departamento` varchar(80) DEFAULT NULL,
  `Municipio` varchar(80) DEFAULT NULL,
  `ZonaHidrografica` varchar(80) DEFAULT NULL,
  `Latitud` varchar(20) DEFAULT NULL,
  `Longitud` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `modelos_datosobtenidos` (
  `indice` varchar(10) DEFAULT NULL,
  `NombreEstacion` varchar(100) DEFAULT NULL,
  `CodigoEstacion` varchar(80) DEFAULT NULL,
  `FechaCompleta` varchar(80) DEFAULT NULL,
  `Fecha` varchar(80) DEFAULT NULL,
  `Hora` varchar(10) DEFAULT NULL,
  `Temperatura_Simulada_Regression` varchar(100) DEFAULT NULL,
  `Temperatura_Simulada_KNN` varchar(100) DEFAULT NULL,
  `Temperatura_Simulada_Red_Neuronal` varchar(100) DEFAULT NULL,
  `Temperatura_Prueba` varchar(100) DEFAULT NULL,
  `Latitud` varchar(100) DEFAULT NULL,
  `Longitud` varchar(100) DEFAULT NULL,
  `Altitud` varchar(100) DEFAULT NULL,
  `Diferencia_Regression` varchar(100) DEFAULT NULL,
  `Diferencia_KNN` varchar(100) DEFAULT NULL,
  `Diferencia_Red_Neuronal` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
SELECT * FROM niote2.modelos_datosobtenidos;
