/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

/*
Relaciones
 */
// Logica
import co.edu.usbbog.datan.niote.controlador.logica.Emulador;
import co.edu.usbbog.datan.niote.controlador.logica.GestionRed;
import co.edu.usbbog.datan.niote.controlador.logica.ValidacionesSistema;

//Emulador (Grafico)
import co.edu.usbbog.datan.niote.vista.media.Graficar;
import co.edu.usbbog.datan.niote.vista.media.Grafos;
import co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosIoTJPanel;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;

//Files
import java.io.File;

import java.nio.file.Files;
import javax.swing.JFileChooser;

//Excepciones 
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

//Explorador de archivos
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Camilo Andres Diaz Gomez
 * @author Jhonatan Villareal
 * @author Juan Esteban Contreras Diaz
 */
public class Principal extends JFrame {

    //Relacion Logica
    private GestionRed gestionRed;
    private ValidacionesSistema validacionesSistema;
    private Emulador emulador;

    //relaciones vista
    private Terminal terminal;

    /*
    Componentes 
     */
    private int tope = 0;//acumulado 
    private int end; // nultimo nodo
    private int start;
    int n = 0, nn = 0, id, id2;
    private int aristM;
    VentanaDialog ventanaDialog;

    PantallaDeCargaJPanel pantallaDeCargaJPanel;

    CrearProyectoJPanel crearProyectoJPanel;
    EmulacionJPanel emulacionJPanel;
    PaletaNodosIoTJPanel paletaSensoresJPanel;

    NotificarErrorJPanel notificarErrorJPanel;
    SobreNosotrosJPanel sobreNosotrosJPanel;

    private Dimension dim;

    /**
     * Creates new form Principal
     */
    public Principal() {
        setTitle("NIOTE");

        setIconImage(new ImageIcon(getClass().getResource("../vista/media/ICONO NIOTE.png")).getImage());
        setName("pricipalJFrame");
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        pack();

        //Centrar ventana
        setLocationRelativeTo(null);

        /*
        Relaciones de logica
         */
        this.pantallaDeCargaJPanel = new PantallaDeCargaJPanel(this);
        this.validacionesSistema = new ValidacionesSistema();
        this.emulador = new Emulador(this);

//        this.setAlwaysOnTop(true);
//        this.setResizable(false);
//        this.setVisible(true);
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int tamanioX = (int) tk.getScreenSize().getWidth();
//        int tamanioY = (int) tk.getScreenSize().getHeight();
//        this.setSize(tamanioX, tamanioY);
//dim=super.getToolkit().getScreenSize();
//        super.setSize(dim);
//        super.setUndecorated(true);
//        super.setVisible(true);
        //Mostrar ventana de carga
        irAPantallaDeCarga();
        //Verificacion de requisitos
        if (pantallaDeCargaJPanel.validacionesMetodo()) {
            //Creacion de carpeta raiz (Donde se guardaran por defecto)
            crearCarpeta();

            // Iniciarlizacion para emulacion (grafico)
            Graficar paint = new Graficar();
            Grafos trees = new Grafos();
            Graficar graph = new Graficar();

            //Inicio
            initComponents();
//            validarBotonesClickeados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        arbolProyectosJPanel1 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.ArbolProyectosJPanel();
        paletaNodosIoTJPanel1 = new co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosIoTJPanel();
        emulacionJPanel1 = new co.edu.usbbog.datan.niote.vista.EmulacionJPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonSave = new javax.swing.JButton();
        jButtonRun = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchive = new javax.swing.JMenu();
        jMenuItemNewProject = new javax.swing.JMenuItem();
        jMenuItemOpenProject = new javax.swing.JMenuItem();
        jMenuItemCloseProject = new javax.swing.JMenuItem();
        jMenuItemCloseAllProjects = new javax.swing.JMenuItem();
        jMenuExport = new javax.swing.JMenu();
        jMenuItemExportToRar = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuExecute = new javax.swing.JMenu();
        jMenuItemRun = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemDocumentation = new javax.swing.JMenuItem();
        jMenuItemReportError = new javax.swing.JMenuItem();
        jMenuItemSearchUpdate = new javax.swing.JMenuItem();
        jMenuItemAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 109, 0));

        jPanel2.setBackground(new java.awt.Color(27, 27, 27));
        jPanel2.setForeground(new java.awt.Color(33, 33, 33));

        jToolBar2.setBackground(new java.awt.Color(45, 45, 45));
        jToolBar2.setRollover(true);

        jButtonSave.setBackground(new java.awt.Color(45, 45, 45));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_save_white_18dp.png"))); // NOI18N
        jButtonSave.setFocusable(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonSave);

        jButtonRun.setBackground(new java.awt.Color(45, 45, 45));
        jButtonRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_play_arrow_white_24dp.png"))); // NOI18N
        jButtonRun.setBorder(null);
        jButtonRun.setBorderPainted(false);
        jButtonRun.setContentAreaFilled(false);
        jButtonRun.setFocusable(false);
        jButtonRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButtonRun);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arbolProyectosJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emulacionJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(paletaNodosIoTJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arbolProyectosJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paletaNodosIoTJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(emulacionJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(27, 27, 27));
        jMenuBar1.setBorder(null);

        jMenuArchive.setBackground(new java.awt.Color(45, 45, 45));
        jMenuArchive.setText("Archivo");

        jMenuItemNewProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNewProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_create_new_folder_black_18dp.png"))); // NOI18N
        jMenuItemNewProject.setText("Nuevo proyecto");
        jMenuItemNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewProjectActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemNewProject);

        jMenuItemOpenProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_folder_open_black_18dp.png"))); // NOI18N
        jMenuItemOpenProject.setText("Abrir proyecto");
        jMenuItemOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenProjectActionPerformed(evt);
            }
        });
        jMenuArchive.add(jMenuItemOpenProject);

        jMenuItemCloseProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCloseProject.setBackground(new java.awt.Color(45, 45, 45));
        jMenuItemCloseProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_cancel_presentation_black_18dp.png"))); // NOI18N
        jMenuItemCloseProject.setText("Cerrar proyecto");
        jMenuArchive.add(jMenuItemCloseProject);

        jMenuItemCloseAllProjects.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCloseAllProjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_cancel_presentation_black_18dp.png"))); // NOI18N
        jMenuItemCloseAllProjects.setText("Cerrar todos los proyectos");
        jMenuArchive.add(jMenuItemCloseAllProjects);

        jMenuExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_import_export_black_18dp.png"))); // NOI18N
        jMenuExport.setText("Exportar");

        jMenuItemExportToRar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/rar-outline (1).png"))); // NOI18N
        jMenuItemExportToRar.setText("a .rar");
        jMenuExport.add(jMenuItemExportToRar);

        jMenuArchive.add(jMenuExport);

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_exit_to_app_black_18dp.png"))); // NOI18N
        jMenuItemExit.setText("Salir");
        jMenuArchive.add(jMenuItemExit);

        jMenuBar1.add(jMenuArchive);
        jMenuArchive.getAccessibleContext().setAccessibleDescription("");

        jMenuEdit.setText("Editar");

        jMenuItem4.setText("Borrar proyecto");
        jMenuEdit.add(jMenuItem4);

        jMenuBar1.add(jMenuEdit);

        jMenuExecute.setText("Ejecutar");

        jMenuItemRun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_play_arrow_black_18dp.png"))); // NOI18N
        jMenuItemRun.setText("Ejecutar");
        jMenuItemRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRunActionPerformed(evt);
            }
        });
        jMenuExecute.add(jMenuItemRun);

        jMenuBar1.add(jMenuExecute);

        jMenuHelp.setText("Ayuda");

        jMenuItemDocumentation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_description_black_18dp.png"))); // NOI18N
        jMenuItemDocumentation.setText("Documentacion (Proximamente...)");
        jMenuHelp.add(jMenuItemDocumentation);

        jMenuItemReportError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_notification_important_black_18dp.png"))); // NOI18N
        jMenuItemReportError.setText("Reportar error");
        jMenuItemReportError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportErrorActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemReportError);

        jMenuItemSearchUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/vista/media/baseline_youtube_searched_for_black_18dp.png"))); // NOI18N
        jMenuItemSearchUpdate.setText("Buscar actualizaciones");
        jMenuHelp.add(jMenuItemSearchUpdate);

        jMenuItemAboutUs.setText("Sobre nosotros");
        jMenuItemAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutUsActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAboutUs);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewProjectActionPerformed
        irACrearProyecto();
    }//GEN-LAST:event_jMenuItemNewProjectActionPerformed

    private void jMenuItemOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenProjectActionPerformed
//Falta leer el archivo y guardarlo en una estructura de datos 
//Draw and drop  Arrastrar y soltar
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File archivoSeleccionado = chooser.getSelectedFile();
        String ruta = null;
        try {
            String tipodeArchivo = Files.probeContentType(archivoSeleccionado.toPath());
            if (tipodeArchivo.equals(".niote")) {
                cargarRed(ruta, ".niote");
                System.out.println("Se cargo");
            } else {

            }
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("No se cargo");
//REVISAR
        } catch (NullPointerException ex2) {
            System.out.println("No se cargo2");
        }
        /* if (archivoSeleccionado!=null) {
            ruta.setText(archivoSeleccionado.getAbsolutePath());
        }*/
        String archivo;
        //  jTreeProjects.add(archivo);
    }//GEN-LAST:event_jMenuItemOpenProjectActionPerformed

    private void jMenuItemAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutUsActionPerformed
        irASobreNosotros();
    }//GEN-LAST:event_jMenuItemAboutUsActionPerformed

    private void jMenuItemReportErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportErrorActionPerformed
        irAReportarError();
    }//GEN-LAST:event_jMenuItemReportErrorActionPerformed

    private void jMenuItemRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRunActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        Principal principal = new Principal();
    }*/
    public GestionRed getGestionRed() {
        return gestionRed;
    }

    public Terminal getTerminal() {
        return terminal;
    }

    public ValidacionesSistema getValidacionesSistema() {
        return validacionesSistema;
    }

    public Emulador getEmulador() {
        return emulador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.ArbolProyectosJPanel arbolProyectosJPanel1;
    private co.edu.usbbog.datan.niote.vista.EmulacionJPanel emulacionJPanel1;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JMenu jMenuArchive;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuExecute;
    private javax.swing.JMenu jMenuExport;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAboutUs;
    private javax.swing.JMenuItem jMenuItemCloseAllProjects;
    private javax.swing.JMenuItem jMenuItemCloseProject;
    private javax.swing.JMenuItem jMenuItemDocumentation;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemExportToRar;
    private javax.swing.JMenuItem jMenuItemNewProject;
    private javax.swing.JMenuItem jMenuItemOpenProject;
    private javax.swing.JMenuItem jMenuItemReportError;
    private javax.swing.JMenuItem jMenuItemRun;
    private javax.swing.JMenuItem jMenuItemSearchUpdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar2;
    private co.edu.usbbog.datan.niote.recursos.pantallaPrincipal.PaletaNodosIoTJPanel paletaNodosIoTJPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    //Navegacion desde inicio
    public void iniciar(JFrame jFrame) {
        remove(jFrame);
        crearProyectoJPanel = new CrearProyectoJPanel(this);
        crearProyectoJPanel.setVisible(true);
        add(crearProyectoJPanel);
        pack();
        setLocationRelativeTo(null);
    }

    private void crearCarpeta() {
        String ubicacion = "C:\\Users\\Camilo y Roberth\\Documents\\NIOTE_Projects";
        File carpeta = new File(ubicacion);
        if (carpeta.mkdirs()) {
        } else {
            carpeta.mkdirs();
        }
    }

    protected boolean crearRed(String id, String nombre, String descripcion) {
        this.gestionRed = new GestionRed(id, nombre, descripcion);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    protected boolean cargarRed(String ruta, String nombreArchivo) {
        this.gestionRed = new GestionRed(ruta, nombreArchivo);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    /* public void irAEm(JPanel jPanel) {
        remove(jPanel);
        emulacionJPanel = new EmulacionJPanel(this);
        emulacionJPanel.setVisible(true);
        add(emulacionJPanel);
        pack();
        setLocationRelativeTo(null);
    }

    /*
    Navegacion emergentes
     */
    protected void irACrearProyecto() {
        crearProyectoJPanel = new CrearProyectoJPanel(this);
        ventanaDialog = new VentanaDialog(this, crearProyectoJPanel, "Creacion de nuevo proyecto", false, false, DISPOSE_ON_CLOSE);
    }

//    protected void irAEm(JPanel jPanel) {
//        remove(jPanel);
//        emulacionJPanel = new EmulacionJPanel(this);
//        ventanaDialog = new VentanaDialog(this, emulacionJPanel, "Entorno", false, false, DISPOSE_ON_CLOSE);
//    }
    private void irAPantallaDeCarga() {
        pantallaDeCargaJPanel = new PantallaDeCargaJPanel(this);
        ventanaDialog = new VentanaDialog(this, pantallaDeCargaJPanel, "Pantalla de carga", false, false, DISPOSE_ON_CLOSE);
    }

    protected void irASobreNosotros() {
        sobreNosotrosJPanel = new SobreNosotrosJPanel(this);
        ventanaDialog = new VentanaDialog(this, sobreNosotrosJPanel, "Información sobre nosotros", false, false, DISPOSE_ON_CLOSE);
    }

    protected void irAReportarError() {
        notificarErrorJPanel = new NotificarErrorJPanel(this);
        ventanaDialog = new VentanaDialog(this, notificarErrorJPanel, "Notificar error", false, false, DISPOSE_ON_CLOSE);
    }

    protected void cerrarVentana() {
        ventanaDialog.dispose();
        ventanaDialog = null;
        //  irAHome();
    }

    //String auxiliar=proyectos;
    protected void metodoParaAgregarAlJTree(String nomProyecto) {
        /*  String proyectos=null;
        proyectos+="Proyectos\n";
        if (rootPaneCheckingEnabled) {
            proyectos+=nombreProyecto+"\n";
            
        }*/
    }

    private void validarBotonesClickeados() {
        java.awt.event.KeyEvent evt = null;
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_F5) {
            jButtonRun.doClick();
        }
    }

}
