/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.datan.niote.vista;

/*
Relaciones
 */
// Logica
import co.edu.usbbog.datan.niote.controlador.logica.Emulador;
import co.edu.usbbog.datan.niote.controlador.logica.GestionRed;
import co.edu.usbbog.datan.niote.controlador.logica.ValidacionesSistema;

//Emulador (Grafico)
import co.edu.usbbog.datan.niote.recursos.Graficar;
import co.edu.usbbog.datan.niote.recursos.Grafos;

//Files
import java.io.File;

import java.nio.file.Files;
import javax.swing.JFileChooser;

//Excepciones 
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

//Explorador de archivos
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Camilo Andres Diaz Gomez
 * @author Jhonatan Villareal
 * @author Juan Esteban Contreras Diaz
 */
public class Principal extends JFrame {

    //Relacion Logica
    private GestionRed gestionRed;
    private ValidacionesSistema validacionesSistema;
    private Emulador emulador;

    //relaciones vista
    private Terminal terminal;

    /*
    Componentes 
     */
    private int tope = 0;//acumulado 
    private int end; // nultimo nodo
    private int start;
    int n = 0, nn = 0, id, id2;
    private int aristM;
    VentanaDialog ventanaDialog;

    public CrearProyectoJPanel crearProyectoJPanel;
    EmulacionJPanel emulacionJPanel;

    /**
     * Creates new form Principal
     */
    public Principal() {

        this.validacionesSistema = new ValidacionesSistema();
        this.emulador = new Emulador(this);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("NIOTE");
        setIconImage(new ImageIcon(getClass().getResource("../recursos/ICONO NIOTE.png")).getImage());
        setName("pricipalJFrame");
        setResizable(false);
        pack();

        //Central ventana
        setLocationRelativeTo(null);

        //Creacion de carpeta raiz (Donde se guardaran por defecto)
        crearCarpeta();

        // Iniciarlizacion para emulacion (grafico)
        Graficar paint = new Graficar();
        Grafos trees = new Grafos();
        Graficar graph = new Graficar();

        //Inicio
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelVersion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevoProyecto = new javax.swing.JMenuItem();
        jMenuItemAbrirProyecto = new javax.swing.JMenuItem();
        jMenuItemCerrarProyecto = new javax.swing.JMenuItem();
        jMenuItemCerrarTodo = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuEjecutar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 109, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(33, 33, 33));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/datan/niote/recursos/NIOTE CON O TransitoriaPNG.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Obtener informacion");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setText("Sobre nosotros");

        jLabelVersion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelVersion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion.setText("Version 1.0 ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabelVersion)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabelVersion))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevoProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevoProyecto.setText("Nuevo proyecto");
        jMenuItemNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoProyectoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevoProyecto);

        jMenuItemAbrirProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAbrirProyecto.setText("Abrir proyecto");
        jMenuItemAbrirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirProyectoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAbrirProyecto);

        jMenuItemCerrarProyecto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCerrarProyecto.setText("Cerrar proyecto");
        jMenuArchivo.add(jMenuItemCerrarProyecto);

        jMenuItemCerrarTodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCerrarTodo.setText("Cerrar todos los proyectos");
        jMenuArchivo.add(jMenuItemCerrarTodo);

        jMenuBar1.add(jMenuArchivo);

        jMenuEditar.setText("Editar");
        jMenuBar1.add(jMenuEditar);

        jMenuEjecutar.setText("Ejecutar");
        jMenuBar1.add(jMenuEjecutar);

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Documentacion (Proximamente...)");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Reportar error");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Buscar actualizaciones");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoProyectoActionPerformed
        irACrearProyecto();
    }//GEN-LAST:event_jMenuItemNuevoProyectoActionPerformed

    private void jMenuItemAbrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirProyectoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);
        File archivoSeleccionado = chooser.getSelectedFile();
        String ruta = null;
        try {
            String tipodeArchivo = Files.probeContentType(archivoSeleccionado.toPath());
            if (tipodeArchivo.equals(".niote")) {

            } else {

            }
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            //REVISAR
        } catch (NullPointerException ex2) {
        }
        /* if (archivoSeleccionado!=null) {
            ruta.setText(archivoSeleccionado.getAbsolutePath());
        }*/
        String archivo;
        //  jTreeProjects.add(archivo);
    }//GEN-LAST:event_jMenuItemAbrirProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        Principal principal = new Principal();
    }*/
    public GestionRed getGestionRed() {
        return gestionRed;
    }

    public Terminal getTerminal() {
        return terminal;
    }

    public ValidacionesSistema getValidacionesSistema() {
        return validacionesSistema;
    }

    public Emulador getEmulador() {
        return emulador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuEjecutar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAbrirProyecto;
    private javax.swing.JMenuItem jMenuItemCerrarProyecto;
    private javax.swing.JMenuItem jMenuItemCerrarTodo;
    private javax.swing.JMenuItem jMenuItemNuevoProyecto;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    //Navegacion desde inicio
    public void iniciar(JFrame jFrame) {
        remove(jFrame);
        crearProyectoJPanel = new CrearProyectoJPanel(this);
        crearProyectoJPanel.setVisible(true);
        add(crearProyectoJPanel);
        pack();
        setLocationRelativeTo(null);
    }

    private void crearCarpeta() {
        String ubicacion = "C:\\Users\\Camilo y Roberth\\Documents\\NIOTE_Projects";
        File carpeta = new File(ubicacion);
        if (carpeta.mkdirs()) {
        } else {
            carpeta.mkdirs();
        }
    }

    protected boolean crearRed(String id, String nombre, String descripcion) {
        this.gestionRed = new GestionRed(id, nombre, descripcion);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    protected boolean cargarRed(String ruta, String nombreArchivo) {
        this.gestionRed = new GestionRed(ruta, nombreArchivo);
        if (this.gestionRed != null) {
            return true;
        } else {
            return false;
        }
    }

    /* public void irAEm(JPanel jPanel) {
        remove(jPanel);
        emulacionJPanel = new EmulacionJPanel(this);
        emulacionJPanel.setVisible(true);
        add(emulacionJPanel);
        pack();
        setLocationRelativeTo(null);
    }

    /*
    Navegacion emergentes
     */
    protected void irACrearProyecto() {
        crearProyectoJPanel = new CrearProyectoJPanel(this);
        ventanaDialog = new VentanaDialog(this, crearProyectoJPanel, "Ventana", false, false, DISPOSE_ON_CLOSE);
    }

    protected void irAEm() {
        emulacionJPanel = new EmulacionJPanel(this);
        ventanaDialog = new VentanaDialog(this, emulacionJPanel, "Ventana", false, false, DISPOSE_ON_CLOSE);
    }
}
